### ISSUE TITLE
crash on null fields

### ISSUE THREAD

**Issue by eskizyen** [prine/ROJSONParser#1]
I added a function to `class Value<T>` to set a default value

```
class func get(rojsonobject:ROJSONObject, key:String, defaultValue:T) -> T {
    if rojsonobject.getJSONValue(key) == nil {
        return defaultValue
    } else {
        return self.get(rojsonobject, key: key)
    }
}
```

**Comment by prine** [comment]
Thanks @eskizyen 

I have also implemented something quite similar but unfortunately I didn't integrate it in the current commit on github. I'm going to merge your solution with my internal solution for dealing with null values. I was thinking about a more dynamic implementation where it does automatically set the T() as default value. Need to check this later.

**Comment by eskizyen** [comment]
I was thinking the same solution but i couldn't figure it out. going to try it when i have time. And thanks for the library, good job.
